apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-catalog
  namespace: gitops-demo
spec:
  destination:
    namespace: gitops-demo-target
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: 3-kustomize/kustomize
    repoURL: https://github.com/gitops-examples/helm-patterns
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
